my_app_user:
    resource: "@MyAppUserBundle/Resources/config/routing.yml"
    prefix:   /user

pi:
    resource: "@PiBundle/Resources/config/routing.yml"
    prefix:   /pi

app:
    resource: '@AppBundle/Controller/'
    type: annotation
# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register


fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

forum:
    resource: "@PiBundle/Resources/config/forum.yml"
    prefix:   /forum

topic:
    resource: "@PiBundle/Resources/config/routing/topic.yml"
    prefix:   /topic

admin_index:
    resource: "@PiBundle/Resources/config/routing/admin.yml"
    prefix:   /dash

article:
    resource: "@PiBundle/Resources/config/routing/article.yml"
    prefix:   /article

babysitter:
    resource: "@PiBundle/Resources/config/routing/babysitter.yml"
    prefix:   /babysitter

video:
    resource: "@PiBundle/Resources/config/routing/videoback.yml"
    prefix:   /video