commentaire_index:
    path:     /
    defaults: { _controller: "PiBundle:Commentaire:index" }
    methods:  GET

commentaire_show:
    path:     /{id}/show
    defaults: { _controller: "PiBundle:Commentaire:show" }
    methods:  GET

commentaire_new:
    path:     /new
    defaults: { _controller: "PiBundle:Commentaire:new" }
    methods:  [GET, POST]

commentaire_edit:
    path:     /{id}/edit
    defaults: { _controller: "PiBundle:Commentaire:edit" }
    methods:  [GET, POST]

commentaire_delete:
    path:     /{id}/delete
    defaults: { _controller: "PiBundle:Commentaire:delete" }
    methods:  DELETE
