<?php

namespace PiBundle\Repository;

/**
 * suggestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BabySitterRepository extends \Doctrine\ORM\EntityRepository
{
    public function DQLAfficher()//ça marche
    {

        $query =$this->getEntityManager()->createQuery("select b from PiBundle:BabySitter b 
            where b.dateDispo> CURRENT_DATE() ");
        return $query->getResult();
    }


}
