<?php

namespace PiBundle\Repository;

/**
 * avis_conseilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
public function DQLPediatre()
{
    $query=$this->getEntityManager()
        ->createQuery("Select m From PiBundle:ConseilE m 
                Where m.categorie='pediatre'");
    return $query->getResult();
}

    public function DQLGynecologue()
    {
        $query=$this->getEntityManager()
            ->createQuery("Select m From PiBundle:ConseilE m 
                Where m.categorie='gynecologue'");
        return $query->getResult();
    }
    public function DQLNutritionniste()
    {
        $query=$this->getEntityManager()
            ->createQuery("Select m From PiBundle:ConseilE m 
                Where m.categorie='nutritionniste'");
        return $query->getResult();
    }
    public function DQLSexologue()
    {
        $query=$this->getEntityManager()
            ->createQuery("Select m From PiBundle:ConseilE m 
                Where m.categorie='sexologue'");
        return $query->getResult();
    }
    public function DQLPsychologue()
    {
        $query=$this->getEntityManager()
            ->createQuery("Select m From PiBundle:ConseilE m 
                Where m.categorie='psychologue'");
        return $query->getResult();
    }
}
