<?php

namespace PiBundle\Repository;

/**
 * suggestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuggestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function AfficherFestivalDql()
    {
        $query=$this->getEntityManager()
            ->createQuery("Select s From PiBundle:Suggestion s 
                Where s.type ='Festival' ");
        return $query->getResult();


    }


    public function AfficherEventDql()
    {
        $query=$this->getEntityManager()
            ->createQuery("Select s From PiBundle:Suggestion s 
                Where s.type ='Event' ");
        return $query->getResult();


    }


    public function findSuggestionDql($adresse){

        $query=$this->getEntityManager()
            ->createQuery("Select s From PiBundle:Suggestion s 
                Where s.adresse Like :adresse ")
            ->setParameter('adresse','%'.$adresse.'%');
        return $query->getResult();

    }


}
